export const georgia = {
  code: "GEL",
  quantity: 1,
  rate: 1,
  name: "ქართული ლარი",
  nameENG: "Georgian Lari",
  countryCode3: "GEO",
  countryCode2: "GE",
  countryName: "Georgia",
  flag: "https://flagsapi.com/GE/flat/64.png",
};

export const excludeCurr = ["EUR", "USD", "RUB", "AZN", "TRY", "GBP"];

export const countryData = [
  {
    country: "United States",
    countryCode2: "US",
    countryCode3: "USA",
    currencyName: "US Dollar",
    currencyCode: "USD",
  },
  {
    country: "Turkey",
    countryCode2: "TR",
    countryCode3: "TUR",
    currencyName: "Turkish Lira",
    currencyCode: "TRY",
  },
  {
    country: "Russian Federation",
    countryCode2: "RU",
    countryCode3: "RUS",
    currencyName: "Russian Federation Ruble",
    currencyCode: "RUB",
  },
  {
    country: "United Kingdom",
    countryCode2: "GB",
    countryCode3: "GBR",
    currencyName: "UK Pound Sterling",
    currencyCode: "GBP",
  },
  {
    country: "Azerbaijan",
    countryCode2: "AZ",
    countryCode3: "AZE",
    currencyName: "Azerbaijani Manat",
    currencyCode: "AZN",
  },
  {
    country: "United Arab Emirates",
    countryCode2: "AE",
    countryCode3: "ARE",
    currencyName: "United Arab Emirates Dirham",
    currencyCode: "AED",
  },
  {
    country: "Armenia",
    countryCode2: "AM",
    countryCode3: "ARM",
    currencyName: "Armenian Dram",
    currencyCode: "AMD",
  },
  {
    country: "Australia",
    countryCode2: "AU",
    countryCode3: "AUS",
    currencyName: "Australian Dollar",
    currencyCode: "AUD",
  },
  {
    country: "Bulgaria",
    countryCode2: "BG",
    countryCode3: "BGR",
    currencyName: "Bulgarian Lev",
    currencyCode: "BGN",
  },
  {
    country: "Brazil",
    countryCode2: "BR",
    countryCode3: "BRA",
    currencyName: "Brazilian Real",
    currencyCode: "BRL",
  },
  {
    country: "Belarus",
    countryCode2: "BY",
    countryCode3: "BLR",
    currencyName: "Belarusian Ruble",
    currencyCode: "BYN",
  },
  {
    country: "Canada",
    countryCode2: "CA",
    countryCode3: "CAN",
    currencyName: "Canadian Dollar",
    currencyCode: "CAD",
  },
  {
    country: "Switzerland",
    countryCode2: "CH",
    countryCode3: "CHE",
    currencyName: "Swiss Franc",
    currencyCode: "CHF",
  },
  {
    country: "China",
    countryCode2: "CN",
    countryCode3: "CHN",
    currencyName: "Chinese Yuan",
    currencyCode: "CNY",
  },
  {
    country: "Czech Republic",
    countryCode2: "CZ",
    countryCode3: "CZE",
    currencyName: "Czech Republic Koruna",
    currencyCode: "CZK",
  },
  {
    country: "Denmark",
    countryCode2: "DK",
    countryCode3: "DNK",
    currencyName: "Danish Krone",
    currencyCode: "DKK",
  },
  {
    country: "Egypt",
    countryCode2: "EG",
    countryCode3: "EGY",
    currencyName: "Egyptian Pound",
    currencyCode: "EGP",
  },
  {
    country: "Hong Kong",
    countryCode2: "HK",
    countryCode3: "HKG",
    currencyName: "Hong Kong Dollar",
    currencyCode: "HKD",
  },
  {
    country: "Hungary",
    countryCode2: "HU",
    countryCode3: "HUN",
    currencyName: "Hungarian Forint",
    currencyCode: "HUF",
  },
  {
    country: "Israel",
    countryCode2: "IL",
    countryCode3: "ISR",
    currencyName: "Israeli New Sheqel",
    currencyCode: "ILS",
  },
  {
    country: "India",
    countryCode2: "IN",
    countryCode3: "IND",
    currencyName: "Indian Rupee",
    currencyCode: "INR",
  },
  {
    country: "Iran",
    countryCode2: "IR",
    countryCode3: "IRN",
    currencyName: "Iranian Rial",
    currencyCode: "IRR",
  },
  {
    country: "Iceland",
    countryCode2: "IS",
    countryCode3: "ISL",
    currencyName: "Icelandic Króna",
    currencyCode: "ISK",
  },
  {
    country: "Japan",
    countryCode2: "JP",
    countryCode3: "JPN",
    currencyName: "Japanese Yen",
    currencyCode: "JPY",
  },
  {
    country: "Kyrgyzstan",
    countryCode2: "KG",
    countryCode3: "KGZ",
    currencyName: "Kyrgystani Som",
    currencyCode: "KGS",
  },
  {
    country: "South Korea",
    countryCode2: "KR",
    countryCode3: "KOR",
    currencyName: "South Korean Won",
    currencyCode: "KRW",
  },
  {
    country: "Kuwait",
    countryCode2: "KW",
    countryCode3: "KWT",
    currencyName: "Kuwaiti Dinar",
    currencyCode: "KWD",
  },
  {
    country: "Kazakhstan",
    countryCode2: "KZ",
    countryCode3: "KAZ",
    currencyName: "Kazakhstani Tenge",
    currencyCode: "KZT",
  },
  {
    country: "Moldova",
    countryCode2: "MD",
    countryCode3: "MDA",
    currencyName: "Moldovan Leu",
    currencyCode: "MDL",
  },
  {
    country: "Norway",
    countryCode2: "NO",
    countryCode3: "NOR",
    currencyName: "Norwegian Krone",
    currencyCode: "NOK",
  },
  {
    country: "New Zealand",
    countryCode2: "NZ",
    countryCode3: "NZL",
    currencyName: "New Zealand Dollar",
    currencyCode: "NZD",
  },
  {
    country: "Poland",
    countryCode2: "PL",
    countryCode3: "POL",
    currencyName: "Polish Zloty",
    currencyCode: "PLN",
  },
  {
    country: "Qatar",
    countryCode2: "QA",
    countryCode3: "QAT",
    currencyName: "Qatari Rial",
    currencyCode: "QAR",
  },
  {
    country: "Romania",
    countryCode2: "RO",
    countryCode3: "ROU",
    currencyName: "Romanian Leu",
    currencyCode: "RON",
  },
  {
    country: "Serbia",
    countryCode2: "RS",
    countryCode3: "SRB",
    currencyName: "Serbian Dinar",
    currencyCode: "RSD",
  },
  {
    country: "Sweden",
    countryCode2: "SE",
    countryCode3: "SWE",
    currencyName: "Swedish Krona",
    currencyCode: "SEK",
  },
  {
    country: "Singapore",
    countryCode2: "SG",
    countryCode3: "SGP",
    currencyName: "Singapore Dollar",
    currencyCode: "SGD",
  },
  {
    country: "Tajikistan",
    countryCode2: "TJ",
    countryCode3: "TJK",
    currencyName: "Tajikistani Somoni",
    currencyCode: "TJS",
  },
  {
    country: "Turkmenistan",
    countryCode2: "TM",
    countryCode3: "TKM",
    currencyName: "Turkmenistani Manat",
    currencyCode: "TMT",
  },
  {
    country: "Ukraine",
    countryCode2: "UA",
    countryCode3: "UKR",
    currencyName: "Ukrainian Hryvnia",
    currencyCode: "UAH",
  },
  {
    country: "Uzbekistan",
    countryCode2: "UZ",
    countryCode3: "UZB",
    currencyName: "Uzbekistan Som",
    currencyCode: "UZS",
  },
  {
    country: "South Africa",
    countryCode2: "ZA",
    countryCode3: "ZAF",
    currencyName: "South African Rand",
    currencyCode: "ZAR",
  },
];

export const url = "https://nbg.gov.ge/gw/api/ct/monetarypolicy/currencies/ka/json/";
