export default [
  {
    id: 101,
    name: "Hittite Warrior from Karkhemishi",
    price: 27,
    image: "1.png",
    colors: ["#00A1D1"],
    artist: "tsotneforester",
    shipping: true,
    category: "millitary",
  },
  {
    id: 102,
    name: "Saint Spyridon, Bishop of Trimythous",
    price: 27,
    image: "2.png",
    colors: ["#003929"],
    artist: "tsotneforester",
    shipping: true,
    category: "holly",
  },
  {
    id: 103,
    name: "the kids from room 402 - Polly McShane",
    price: 33,
    image: "3.png",
    colors: ["#0D2942"],
    artist: "tsotneforester",
    shipping: true,
    category: "cartoon",
  },
  {
    id: 104,
    name: "Spartain helmet",
    price: 24,
    image: "4.png",
    colors: ["#E9DB56"],
    artist: "tsotneforester",
    shipping: false,
    category: "military",
  },
  {
    id: 105,
    name: "Vaja-Pshavela Portrait",
    price: 38,
    image: "5.png",
    colors: ["#0D2942"],
    artist: "tsotneforester",
    shipping: true,
    category: "literature",
  },
  {
    id: 106,
    name: "ERI Logo",
    price: 17,
    image: "6.png",
    colors: ["#2658B8"],
    artist: "tsotneforester",
    shipping: true,
    category: "",
  },
  {
    id: 107,
    name: "Ancient Georgian Orthodox Carving",
    price: 22,
    image: "7.png",
    colors: ["#1D1E1D"],
    artist: "tsotneforester",
    shipping: true,
    category: "",
  },
  {
    id: 108,
    name: "DOM & Jquery (Tom & Jerry)",
    price: 35,
    image: "8.png",
    colors: ["#00A1D1"],
    artist: "dom and jquerry",
    shipping: true,
    category: "cartoon",
  },
  {
    id: 109,
    name: "Bavri Church Relief",
    price: 24,
    image: "9.png",
    colors: ["#003929"],
    artist: "tsotneforester",
    shipping: true,
    category: "holly",
  },
  {
    id: 110,
    name: "Gergeti Trinity & Mkinvartsveri",
    price: 16,
    image: "10.png",
    colors: ["#D8520D"],
    artist: "tsotneforester",
    shipping: true,
    category: "holly",
  },
  {
    id: 111,
    name: "Fridon Sulaberidze Dancing Kintauri",
    price: 20,
    image: "11.png",
    colors: ["#E9DB56"],
    artist: "fridoni",
    shipping: false,
    category: "celebs",
  },
  {
    id: 112,
    name: "Uncle Pecos Singing",
    price: 29,
    image: "12.png",
    colors: ["#0D2942"],
    artist: "crambooo",
    shipping: true,
    category: "cartoon",
  },
  {
    id: 113,
    name: "Samtavro Monastery Relief",
    price: 26,
    image: "13.png",
    colors: ["#00A1D1"],
    artist: "tsotneforester",
    shipping: true,
    category: "holly",
  },
  {
    id: 114,
    name: "Chess Legend - Nona Gaprindashvili",
    price: 39,
    image: "14.png",
    colors: ["#FFF"],
    artist: "tsotneforester",
    shipping: true,
    category: "celebs",
  },
  {
    id: 115,
    name: "Ancient Georgian Carving",
    price: 18,
    image: "15.png",
    colors: ["#1D1E1D"],
    artist: "tsotneforester",
    shipping: false,
    category: "",
  },
  {
    id: 116,
    name: "Jesus Christ abreviation",
    price: 25,
    image: "16.png",
    colors: ["#5B489D"],
    artist: "tsotneforester",
    shipping: true,
    category: "holly",
  },
  {
    id: 117,
    name: "Tron Legacy - Reconfigured",
    price: 36,
    image: "17.png",
    colors: ["#FFF"],
    artist: "tsotneforester",
    shipping: true,
    category: "music",
  },
  {
    id: 118,
    name: "Digital Carving",
    price: 31,
    image: "18.png",
    colors: ["#D60027"],
    artist: "tsotneforester",
    shipping: true,
    category: "",
  },
  {
    id: 119,
    name: "Ertoba, Raoba, Imedi",
    price: 23,
    image: "19.png",
    colors: ["#524025"],
    artist: "tsotneforester",
    shipping: true,
    category: "",
  },
  {
    id: 120,
    name: "Akaki Tsereteli, Vaja-Pshavela, Ilia Chavchavadze",
    price: 37,
    image: "20.png",
    colors: ["#1D1E1D"],
    artist: "tsotneforester",
    shipping: true,
    category: "literature",
  },
  {
    id: 121,
    name: "Weeknd & Daft Punk - Starboy",
    price: 28,
    image: "21.png",
    colors: ["#00A1D1"],
    artist: "tsotneforester",
    shipping: true,
    category: "music",
  },
  {
    id: 122,
    name: "Call Of Duty 2 Logo",
    price: 32,
    image: "22.png",
    colors: ["#1D1E1D"],
    artist: "tsotneforester",
    shipping: false,
    category: "game",
  },
  {
    id: 123,
    name: "King Erekle II of Georgia",
    price: 21,
    image: "23.png",
    colors: ["#0D2942"],
    artist: "tsotneforester",
    shipping: true,
    category: "celebs",
  },
  {
    id: 124,
    name: "Tatevi Monastery Relief",
    price: 18,
    image: "24.png",
    colors: ["#D8520D"],
    artist: "tsotneforester",
    shipping: true,
    category: "holly",
  },
  {
    id: 125,
    name: "Cross",
    price: 15,
    image: "25.png",
    colors: ["#FB7598"],
    artist: "tsotneforester",
    shipping: true,
    category: "holly",
  },
  {
    id: 126,
    name: "The Iron Giant Portrait",
    price: 40,
    image: "26.png",
    colors: ["#FA0022"],
    artist: "tsotneforester",
    shipping: false,
    category: "cartoon",
  },
  {
    id: 127,
    name: "Aleksandre kazbegi Portrait",
    price: 28,
    image: "27.png",
    colors: ["#FFF"],
    artist: "tsotneforester",
    shipping: true,
    category: "literature",
  },
  {
    id: 128,
    name: "Aleksandre kazbegi Portrait & Signature",
    price: 16,
    image: "28.png",
    colors: ["#E9DB56"],
    artist: "tsotneforester",
    shipping: true,
    category: "literature",
  },
  {
    id: 129,
    name: "Aleksandre kazbegi Portrait",
    price: 37,
    image: "29.png",
    colors: ["#FA0022"],
    artist: "tsotneforester",
    shipping: true,
    category: "literature",
  },
  {
    id: 130,
    name: "Gorillaz Windmill",
    price: 19,
    image: "30.png",
    colors: ["#003929"],
    artist: "tsotneforester",
    shipping: true,
    category: "music",
  },
  {
    id: 131,
    name: "Syberia 3 from Sokal",
    price: 22,
    image: "31.png",
    colors: ["#FFF"],
    artist: "tsotneforester",
    shipping: false,
    category: "game",
  },
  {
    id: 132,
    name: "silhouette of Music Instruments",
    price: 31,
    image: "32.png",
    colors: ["#FB7598"],
    artist: "tsotneforester",
    shipping: true,
    category: "music",
  },
  {
    id: 133,
    name: "Don Quixote, Sancho and Windmill",
    price: 39,
    image: "33.png",
    colors: ["#2658B8"],
    artist: "tsotneforester",
    shipping: true,
    category: "literature",
  },
  {
    id: 134,
    name: "The Bremen Town Musicians",
    price: 20,
    image: "34.png",
    colors: ["#FFF"],
    artist: "tsotneforester",
    shipping: true,
    category: "music",
  },
  {
    id: 135,
    name: "Company Of Heroes 3",
    price: 33,
    image: "35.png",
    colors: ["#1D1E1D"],
    artist: "tsotneforester",
    shipping: true,
    category: "game",
  },
  {
    id: 136,
    name: "Death Stranding Spider",
    price: 26,
    image: "36.png",
    colors: ["#2658B8"],
    artist: "tsotneforester",
    shipping: true,
    category: "game",
  },
  {
    id: 137,
    name: "Godzilla",
    price: 23,
    image: "37.png",
    colors: ["#FFF"],
    artist: "tsotneforester",
    shipping: true,
    category: "movie",
  },
  {
    id: 138,
    name: "Godzilla in Tbilisi",
    price: 28,
    image: "38.png",
    colors: ["#524025"],
    artist: "tsotneforester",
    shipping: true,
    category: "movie",
  },
  {
    id: 139,
    name: "The Bremen Town Musicians",
    price: 19,
    image: "39.png",
    colors: ["#00A1D1"],
    artist: "tsotneforester",
    shipping: true,
    category: "cartoon",
  },
  {
    id: 140,
    name: "The Bremen Town Detective",
    price: 32,
    image: "40.png",
    colors: ["#1D1E1D"],
    artist: "bremenelebis gammziebeli",
    shipping: true,
    category: "cartoon",
  },
  {
    id: 141,
    name: "Professor Fate Machine",
    price: 20,
    image: "41.png",
    colors: ["#524025"],
    artist: "tsotneforester",
    shipping: true,
    category: "movie",
  },
  {
    id: 142,
    name: "Medal Of Honor - Airborne",
    price: 26,
    image: "42.png",
    colors: ["#1D1E1D"],
    artist: "tsotneforester",
    shipping: true,
    category: "game",
  },
  {
    id: 143,
    name: "Farcry Universe",
    price: 17,
    image: "43.png",
    colors: ["#1D1E1D"],
    artist: "tsotneforester",
    shipping: true,
    category: "game",
  },
  {
    id: 144,
    name: "AI CUP Chess Logo",
    price: 34,
    image: "44.png",
    colors: ["#524025"],
    artist: "tsotneforester",
    shipping: true,
    category: "sport",
  },
  {
    id: 145,
    name: "Gorillaz album 'Plastic Beach'",
    price: 22,
    image: "45.png",
    colors: ["#FB7598"],
    artist: "tsotneforester",
    shipping: true,
    category: "music",
  },
  {
    id: 146,
    name: "Gorillaz",
    price: 25,
    image: "46.png",
    colors: ["#1D1E1D"],
    artist: "tsotneforester",
    shipping: true,
    category: "music",
  },
  {
    id: 147,
    name: "AWP Sniper Rifle",
    price: 25,
    image: "47.png",
    colors: ["#5B489D"],
    artist: "tsotneforester",
    shipping: true,
    category: "military",
  },
  {
    id: 148,
    name: "Ancient Deer Statue",
    price: 31,
    image: "48.png",
    colors: ["#1D1E1D"],
    artist: "tsotneforester",
    shipping: true,
    category: "",
  },
  {
    id: 149,
    name: "Tskhrajvari Church Relief",
    price: 20,
    image: "49.png",
    colors: ["#0D2942"],
    artist: "tsotneforester",
    shipping: true,
    category: "holly",
  },
  {
    id: 150,
    name: "Gergeti Trinity Relief",
    price: 38,
    image: "50.png",
    colors: ["#D60027"],
    artist: "tsotneforester",
    shipping: true,
    category: "holly",
  },
  {
    id: 151,
    name: "Georgian Ornament",
    price: 25,
    image: "51.png",
    colors: ["#003929"],
    artist: "tsotneforester",
    shipping: true,
    category: "ethno",
  },
  {
    id: 152,
    name: "Anthropomorphic figure, North Caucasus",
    price: 34,
    image: "52.png",
    colors: ["#1D1E1D"],
    artist: "tsotneforester",
    shipping: true,
    category: "ethno",
  },
  {
    id: 153,
    name: "Oda In Imereti, Georgia",
    price: 19,
    image: "53.png",
    colors: ["#FFF"],
    artist: "tsotneforester",
    shipping: true,
    category: "ethno",
  },
  {
    id: 154,
    name: "Svaneti, Jakhunderi Ornament",
    price: 35,
    image: "54.png",
    colors: ["#0D2942"],
    artist: "tsotneforester",
    shipping: true,
    category: "ethno",
  },
  {
    id: 155,
    name: "Church, Night, Moon",
    price: 23,
    image: "55.png",
    colors: ["#E9DB56"],
    artist: "tsotneforester",
    shipping: false,
    category: "holly",
  },
  {
    id: 156,
    name: "Dedabodzi, Georgia",
    price: 31,
    image: "56.png",
    colors: ["#E9DB56"],
    artist: "tsotneforester",
    shipping: false,
    category: "ethno",
  },
  {
    id: 157,
    name: "Cross Ornament",
    price: 35,
    image: "57.png",
    colors: ["#003929"],
    artist: "tsotneforester",
    shipping: false,
    category: "holly",
  },
  {
    id: 158,
    name: "Cross Ornament, Gelati",
    price: 27,
    image: "58.png",
    colors: ["#5B489D"],
    artist: "tsotneforester",
    shipping: false,
    category: "holly",
  },
  {
    id: 159,
    name: "Angel Ornament",
    price: 18,
    image: "59.png",
    colors: ["#D8520D"],
    artist: "tsotneforester",
    shipping: false,
    category: "holly",
  },
  {
    id: 160,
    name: "Imeretian Sketches",
    price: 34,
    image: "60.png",
    colors: ["#E9DB56"],
    artist: "tsotneforester",
    shipping: false,
    category: "movie",
  },
  {
    id: 161,
    name: "Kung Fu Panda",
    price: 27,
    image: "61.png",
    colors: ["#FFF"],
    artist: "tsotneforester",
    shipping: true,
    category: "cartoon",
  },
  {
    id: 162,
    name: "The Sunny Night - Nodar Dumbadze",
    price: 20,
    image: "62.png",
    colors: ["#524025"],
    artist: "tsotneforester",
    shipping: true,
    category: "literature",
  },
  {
    id: 163,
    name: "Kakhi Kavsadze",
    price: 36,
    image: "63.png",
    colors: ["#D60027"],
    artist: "tsotneforester",
    shipping: false,
    category: "celebs",
  },
  {
    id: 164,
    name: "Meeting in Mountain",
    price: 22,
    image: "64.png",
    colors: ["#FFF"],
    artist: "tsotneforester",
    shipping: true,
    category: "movie",
  },
  {
    id: 165,
    name: "Vineyard",
    price: 28,
    image: "65.png",
    colors: ["#1D1E1D"],
    artist: "tsotneforester",
    shipping: false,
    category: "ethno",
  },
  {
    id: 166,
    name: "Never To Nuclear weapon",
    price: 35,
    image: "66.png",
    colors: ["#0D2942"],
    artist: "tsotneforester",
    shipping: false,
    category: "military",
  },
  {
    id: 167,
    name: "Sherekilebi",
    price: 21,
    image: "67.png",
    colors: ["#00A1D1"],
    artist: "tsotneforester",
    shipping: false,
    category: "movie",
  },
  {
    id: 168,
    name: "Krimanchuli",
    price: 31,
    image: "68.png",
    colors: ["#1D1E1D"],
    artist: "tsotneforester",
    shipping: false,
    category: "ethno",
  },
  {
    id: 169,
    name: "Kartlis Deda",
    price: 35,
    image: "69.png",
    colors: ["#D60027"],
    artist: "tsotneforester",
    shipping: false,
    category: "ethno",
  },
  {
    id: 170,
    name: "Georgian Folk Dancer",
    price: 16,
    image: "70.png",
    colors: ["#1D1E1D"],
    artist: "tsotneforester",
    shipping: true,
    category: "ethno",
  },
  {
    id: 171,
    name: "Church",
    price: 23,
    image: "71.png",
    colors: ["#00A1D1"],
    artist: "tsotneforester",
    shipping: true,
    category: "holy",
  },
  {
    id: 172,
    name: "Whitesnake",
    price: 29,
    image: "72.png",
    colors: ["#5B489D"],
    artist: "tsotneforester",
    shipping: false,
    category: "music",
  },
  {
    id: 173,
    name: "Nikortsminda Chapel",
    price: 34,
    image: "73.png",
    colors: ["#FFF"],
    artist: "tsotneforester",
    shipping: false,
    category: "ethno",
  },
  {
    id: 174,
    name: "Fat Joe, Slim Joe",
    price: 36,
    image: "74.png",
    colors: ["#FFF"],
    artist: "tsotneforester",
    shipping: true,
    category: "chest",
  },
  {
    id: 175,
    name: "Shatili, Svaneti, Georgia",
    price: 25,
    image: "75.png",
    colors: ["#FFF"],
    artist: "tsotneforester",
    shipping: true,
    category: "chest",
  },
  {
    id: 176,
    name: "Mtkheta, Georgia",
    price: 29,
    image: "76.png",
    colors: ["#00A1D1"],
    artist: "tsotneforester",
    shipping: true,
    category: "chest",
  },
  {
    id: 177,
    name: "Cucaracha, Georgian movie",
    price: 34,
    image: "77.png",
    colors: ["#00A1D1"],
    artist: "tsotneforester",
    shipping: true,
    category: "movie",
  },
  {
    id: 178,
    name: "Whitesnake",
    price: 16,
    image: "78.png",
    colors: ["#524025"],
    artist: "tsotneforester",
    shipping: true,
    category: "music",
  },
  {
    id: 179,
    name: "Architecture Drill",
    price: 23,
    image: "98.png",
    colors: ["#1D1E1D"],
    artist: "tsotneforester",
    shipping: true,
    category: "chest",
  },
];

//literature
// holly
// cartoon
// game
// music
// movie
// celebs
